version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile-server
        image: recipe-server-api:latest
        ports:
            - "5000:5000"
    web:
        build:
            context: .
            dockerfile: Dockerfile-client
        image: recipe-web:latest
        ports:
            - "3000:3000"
